### PR TITLE
fix problem with listvalued fks

### PR DESCRIPTION
**Pull request by xrotwang**

### CODE REVIEW

**Review by tresoldi — APPROVED** [review]

**Comment by xrotwang** [comment]
@tresoldi should we already make a new pylexibank release (for lexicore) - or rather wait a bit?

**Comment by tresoldi** [comment]
I think it is worth waiting, there might be more stuff down the road. I can compile with my clone of pylexibank installed in development mode until then. I should be able to get to lexicore by the end of the day.

**Comment by tresoldi** [comment]
@xrotwang unfortunately it is still not working, not sure why my earlier test seemed ok.

```bash
(fresh environment)
$ pip install -e git+https://github.com/lexibank/pylexibank.git#egg=pylexibank
$ pip install -e git+https://github.com/lexibank/aaleykusunda.git#egg=lexibank_aaleykusunda
$ pip freeze | grep lexi
-e git+https://github.com/lexibank/aaleykusunda.git@9e6031c71fc0ee0edbd6744a13763d3a8db504ac#egg=lexibank_aaleykusunda
-e git+https://github.com/lexibank/pylexibank.git@8b6d94642ab75b7a32044d0e146cd028454adc41#egg=pylexibank
$ cldfbench lexibank.load _ --glottolog /home/tresoldi/.config/cldf/glottolog --concepticon /home/tresoldi/.config/cldf/concepticon
[...]
  File "/home/tresoldi/lexibank/lexicore/env/src/pylexibank/src/pylexibank/db.py", line 445, in load
    insert(db, t.name, keys, *rows, **{'verbose': verbose})
  File "/home/tresoldi/lexibank/lexicore/env/src/pylexibank/src/pylexibank/db.py", line 77, in insert
    db.executemany(sql, rows)
sqlite3.IntegrityError: FOREIGN KEY constraint failed
```

**Comment by xrotwang** [comment]
@tresoldi cant confirm:
```
(pylexitest) forkel@shh.mpg.de@dlt4803010l:~/venvs/pylexitest$ cldfbench lexibank.load _
INFO    running load on aaleykusunda ...
Dataset "aaleykusunda" at /home/forkel/venvs/pylexitest/src/lexibank-aaleykusunda
INFO    ... done aaleykusunda [0.2 secs]
(pylexitest) forkel@shh.mpg.de@dlt4803010l:~/venvs/pylexitest$ pip freeze | grep lexi
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
-e git+https://github.com/lexibank/aaleykusunda.git@9e6031c71fc0ee0edbd6744a13763d3a8db504ac#egg=lexibank_aaleykusunda
-e git+https://github.com/lexibank/pylexibank.git@8b6d94642ab75b7a32044d0e146cd028454adc41#egg=pylexibank
```

**Comment by xrotwang** [comment]
Do you get any additional foreign key constraints? Maybe something due to a difference between py3.5 and higher?

**Comment by tresoldi** [comment]
@xrotwang I'm not sure of the reason, but it works under 3.7 with the other datasets. I was trying to run under 3.5 by pinning versions (numpy==1.18.5, csvw==1.5.6, pybtex=0.22.2), but it ended up broken because of the f-strings in `cldfbench`.

However, most important, loading database is still broken, now for `castrosui`:

```
INFO    running load on castrosui ...
Dataset "castrosui" at /home/tresoldi/lexibank/lexicore/env/src/lexibank-castrosui
Traceback (most recent call last):
  File "/home/tresoldi/lexibank/lexicore/env/bin/cldfbench", line 8, in <module>
    sys.exit(main())
  File "/home/tresoldi/lexibank/lexicore/env/lib/python3.7/site-packages/cldfbench/__main__.py", line 78, in main
    return args.main(args) or 0
  File "/home/tresoldi/lexibank/lexicore/env/src/pylexibank/src/pylexibank/commands/load.py", line 17, in run
    with_datasets(args, db.load)
  File "/home/tresoldi/lexibank/lexicore/env/lib/python3.7/site-packages/cldfbench/cli_util.py", line 90, in with_datasets
    res.append(with_dataset(args, func, dataset=ds))
  File "/home/tresoldi/lexibank/lexicore/env/lib/python3.7/site-packages/cldfbench/cli_util.py", line 82, in with_dataset
    res = func(*arg, args)
  File "/home/tresoldi/lexibank/lexicore/env/src/pylexibank/src/pylexibank/db.py", line 378, in load
    t.name, col.name, db_cols[col.name], col.db_type))
KeyError: 'Population'
```

The culprit is here: https://github.com/lexibank/castrosui/blob/master/cldf/languages.csv , given as a string in the metadata.

**Comment by xrotwang** [comment]
Again, I cannot reproduce this:
```
$ pip install -e git+https://github.com/lexibank/castrosui.git#egg=lexibank_castrosui
$ cldfbench lexibank.load _INFO    running load on aaleykusunda ...
Dataset "aaleykusunda" at /home/forkel/venvs/pylexitest/src/lexibank-aaleykusunda
INFO    ... done aaleykusunda [0.1 secs]
INFO    running load on castrosui ...
Dataset "castrosui" at /home/forkel/venvs/pylexitest/src/lexibank-castrosui
INFO    ... done castrosui [1.0 secs]
```

**Comment by xrotwang** [comment]
@tresoldi I think you are running into the problem of `Population` being already defined in the DB as `population` from a different dataset (`abvd` possibly). @chrzyki identified this issue before (see https://github.com/lexibank/pylexibank/issues/224).

**Comment by xrotwang** [comment]
Actually, it's just similar. The error message shadows the real problem, because `population` and `Population` seem to be defined with different datatypes. The code fails here:
```python
                    if db_cols[col.name.lower()] != col.db_type:
                        raise ValueError(
                            'column {0}:{1} {2} redefined with new type {3}'.format(
                                t.name, col.name, db_cols[col.name], col.db_type))
```

**Comment by xrotwang** [comment]
I'm not sure what to do here. If we want to continue with the idea of being able to load multiple datasets into the same DB there must be some sort of coordination of the shared database schema - beyond what we do with the model classes in `pylexibank`. This could be a list of "known" additional properties with datatypes, where `Population` as `integer` might be a candidate.

Thoughts @LinguList @chrzyki @SimonGreenhill ?

**Comment by tresoldi** [comment]
@xrotwang yes, my report should have been clearer, this is only being triggered when all datasets are being loaded (I only pasted the log for `castrosui`, but it was running on the whole of lexicore).

I support having `Population` as an integer. Each dataset (or, more properly, each dataset accepted as a "core" one) that uses it might have a different level of detail and method of reporting, but it is should be a number. If the information is vague ("about X speakers", "between Y and Z speakers", etc.), better to have it as a comment.

**Comment by LinguList** [comment]
If we have a list of known datatypes, could we add them to lexibank, in the sense of having `Segments`? This would hard-code things, but so far, we also do not have too many aspects here, and I think we could even handle things via the CLDF spec?

I am thinking of something like:

```python
from pylexibank.model import Population
```

**Comment by xrotwang** [comment]
@tresoldi could you compile a list of all candidate columns - i.e. columns that appear in at least two lexicore datasets (case-insensitively)?

**Comment by chrzyki** [comment]
I fully agree that a list supported additional fields would be good. Realistically speaking, how many of the 'surplus' columns (i.e. those besides our standard columns) would matter for combined database of Lexibank datasets? Not many analyses are going to uses those, or are they? If the additional columns that would be loaded could in some way be configured during database creation this might also help to keep the SQLite at a somewhat more manageable size.

**Comment by xrotwang** [comment]
To be honest, I'm more concerned about keeping the DB creation code at manageable size.

**Comment by chrzyki** [comment]
If `col.name.lower()` exists with a type and is to be added again with a different type, augment it with type suffix? I.e. `population` and then `population_str`? Kind of a brute force solution, but minimal code required and we could fix datasets wherever/whenever this makes sense.

**Comment by tresoldi** [comment]
Or maybe just drop custom fields?

**Comment by xrotwang** [comment]
I think, I can see three options:
- Since we are working on the datasets right now anyway, normalize **all** columns that appear multiple times. (This will require more changes in datasets, but **no** changes in `pylexibank`.)
- Drop all non-standard columns - i.e. everything that is not a `pylexibank` model attribute. This will probably also require dropping all non-standard tables, because otherwise we'd have to do some checking before creating foreign key constraints ...
- @chrzyki 's proposal - which will also be complicated by the fact that renaming columns is hard since they may be involved in foreign key constraints.

I'm favoring the first option - simply because I fee the code in `pylexibank.db` is fragile enough, and any modification should come with extensive testing.

**Comment by chrzyki** [comment]
Dropping the columns feels wrong, the more I think about it. The first option sounds reasonable. Is this something we could bake into buildbot to trigger warnings on 'not-normalized' columns? I.e. make buildbot run a `cldfbench load _` and check for problematic columns?

**Comment by xrotwang** [comment]
I'd rather have a list in `pylexibank`, enumerating all cases we know about. Maybe we can also adopt some sort of naming convention - as a compromise - e.g. everything starting with `local_` isn't added to the database and must not be in a foreign key relation.

**Comment by tresoldi** [comment]
I am collecting the fields now. BTW, does pylexibank default to the `string` datatype? This property at least has no datatype specified: https://github.com/lexibank/tppsr/blob/4d6ae1c2889e2938036b8d0866370c664fcbdd5a/cldf/cldf-metadata.json#L403

**Comment by SimonGreenhill** [comment]
Agree, populations should be ints. 

For other things, I really like the idea of having the SQLite as a self contained snapshot of the dataset and would hate to have some columns missed because Lexibank didn’t understand them. 

 Can we make an assumption like “if no data type then it’s a string”? Or alternatively can we just serialise anything we don’t know  and then it’s up to the user to parse.

**Comment by LinguList** [comment]
I also favor option `#`1, although, on the long run, we want to have a code that passes WANTED column properties for all fields, not code that sucks in everything. This would then mean: if you WANT population, make sure it is consistent. If NOT, no problem.

This could be done in a configuration file. And this would be different for CLICS than for lexicore.

**Comment by tresoldi** [comment]
Here the properties of datasets: [lexicore.properties.txt](https://github.com/lexibank/pylexibank/files/5443649/lexicore.properties.txt)

**Comment by xrotwang** [comment]
ok, I'll bite the bullet and will look into `pylexibank.db` again. Starting with adding lots more tests. - Unless anyone else wants to?

**Comment by LinguList** [comment]
I do not feel competent enough to look into sqlite questions, I am afraid.

**Comment by xrotwang** [comment]
Ok, so `Population` - once as `integer` and once as `string` seems to be the only problem in need of fixing. And I'd agree that the fix should be renaming the `string` column to `Population_Comment` in `castrosui` and `halenpal` (unless it's a number there as well, then the datatype would need to be adjusted as is done here: https://github.com/lexibank/tppsr/blob/4d6ae1c2889e2938036b8d0866370c664fcbdd5a/lexibank_tppsr.py#L60-L62)

Other than that, we might want to normalize some property names:
```
Languages,Full_Name,string
Languages,FullName,string
Languages,LanguageName,string
Languages,Name_in_Source,string
Languages,NameInSource,string
Languages,Name_in_Text,string
```

**Comment by tresoldi** [comment]
`Population` has integer values in `castrosui` (some are missing). In `halenepal` they are all empty (probably code that was copied and pasted).

`SourceName` or `NameInSource` sound both good.

**Comment by xrotwang** [comment]
Regarding naming conventions: CLDF has Capitalized_Words with underscore. So `Source_Name`, I'd say.

Where should we enforce/validate these less formal constraints? After `makecldf`? Or as separate command?

**Comment by LinguList** [comment]
@xrotwang, one question: the proposal to allow to define when loading what columns should be included, which I made, is that off the table? I think it would be helpful, since it would allow to reduce the space for targeted datasets that do not need to share all CLDF data aspects when loading them to sqlite3.

Furthermore: for the SEA datasets, I tried to have consistent names for recurring attributes (Chinese_Name, Chinese_Gloss, etc.), since they are often submitted along with a dataset. I wonder to which degree we would like to use the experience from there to fix the name space for other datasets as well? In that case, I could make a proposal for aspects of the data that I see as most important, judging from my work with the SEA datasets.

**Comment by xrotwang** [comment]
@LinguList I think configuring what tables/columns to load is too complicated to implement. Maybe we could have a configurable `lexibank.prunedb` command, which drops columns/tables afterwards.

**Comment by chrzyki** [comment]
> 
> 
> Regarding naming conventions: CLDF has Capitalized_Words with underscore. So `Source_Name`, I'd say.
> 
> Where should we enforce/validate these less formal constraints? After `makecldf`? Or as separate command?

I'd say directly after `makecldf`.

**Pull request merged**
