### PR TITLE
Clpa2clts

### PR DESCRIPTION
**Pull request by tresoldi**
This moves from CLPA to CLTS. Coverage increases a little bit for all datasets I've tested it on; there are also some changes in the wording of the reports, preparing for future expansions.

I've tried to modify the code logic as little as possible, even though some underlying assumptions might be valid or necessary anymore. Sound class model is defaulting to `dolgo`, but I've already let a `sca` model in place so we can properly implement multiple sound classes in the future (or maybe we should move directly to `sca`).

### CODE REVIEW

**Comment by LinguList** [comment]
May I ask one favor? This looks all very fine to me, but could we see how a sample output with this looks now, e.g., one markdown file pasted here?

**Comment by tresoldi** [comment]
Sure, here from Bowern Pama-Nyungan (with the matter of the question marks):

# Detailed transcription record

## Segments

| Segment | Occurrence | BIPA | CLTS SoundClass |
|:----------|-------------:|:-------|:------------------|
| a | 57258 | ✓ | ✓ |
| u | 28660 | ✓ | ✓ |
| i | 26250 | ✓ | ✓ |
| n | 14109 | ✓ | ✓ |
| k | 12631 | ✓ | ✓ |
| m | 12341 | ✓ | ✓ |
| l | 11376 | ✓ | ✓ |
| ŋ | 10524 | ✓ | ✓ |
| ɹ | 9360 | ✓ | ✓ |
| r | 8509 | ✓ | ✓ |
| w | 8335 | ✓ | ✓ |
| g | 8303 | ✓ | ✓ |
| b | 8230 | ✓ | ✓ |
| j | 8175 | ✓ | ✓ |
| c | 7859 | ✓ | ✓ |
| p | 7804 | ✓ | ✓ |
| d | 6173 | ✓ | ✓ |
| t | 5513 | ✓ | ✓ |
| e | 3783 | ✓ | ✓ |
| o | 3331 | ✓ | ✓ |
| ɲ | 3239 | ✓ | ✓ |
| t̪ | 2749 | ✓ | ✓ |
| ɳ | 2526 | ✓ | ✓ |
| ɭ | 2159 | ✓ | ✓ |
| _ | 1889 | ✓ | ✓ |
| oː | 1799 | ✓ | ✓ |
| d̪ | 1509 | ✓ | ✓ |
| aː | 1404 | ✓ | ✓ |
| ɖ | 1375 | ✓ | ✓ |
| ʈ | 1350 | ✓ | ✓ |
| n̪ | 999 | ✓ | ✓ |
| ʔ | 923 | ✓ | ✓ |
| lː | 655 | ✓ | ✓ |
| eː | 627 | ✓ | ✓ |
| uː | 562 | ✓ | ✓ |
| h | 492 | ✓ | ✓ |
| nː | 445 | ✓ | ✓ |
| iː | 426 | ✓ | ✓ |
| æ | 259 | ✓ | ✓ |
| tː | 224 | ✓ | ✓ |
| l̪ | 215 | ✓ | ✓ |
| kː | 203 | ✓ | ✓ |
| mː | 150 | ✓ | ✓ |
| v | 150 | ✓ | ✓ |
| pː | 142 | ✓ | ✓ |
| ə | 137 | ✓ | ✓ |
| ɣ | 129 | ✓ | ✓ |
| ɔ | 126 | ✓ | ✓ |
| ? | 117 | ? | ? |
| z | 112 | ✓ | ✓ |
| kʷ | 107 | ✓ | ✓ |
| bː | 97 | ✓ | ✓ |
| ɪ | 93 | ✓ | ✓ |
| q | 91 | ✓ | ✓ |
| ʔʲ | 90 | ✓ | ✓ |
| dː | 81 | ✓ | ✓ |
| gː | 79 | ✓ | ✓ |
| s | 75 | ✓ | ✓ |
| β | 75 | ✓ | ✓ |
| ʊ | 47 | ✓ | ✓ |
| ɽ | 46 | ✓ | ✓ |
| gʷ | 45 | ✓ | ✓ |
| ɛ | 31 | ✓ | ✓ |
| ˀw | 31 | ✓ | ✓ |
| ɨ | 26 | ✓ | ✓ |
| ð | 24 | ✓ | ✓ |
| ˀm | 24 | ✓ | ✓ |
| dʒ | 23 | ✓ | ✓ |
| x | 18 | ✓ | ✓ |
| ˀk | 18 | ✓ | ✓ |
| cː | 16 | ✓ | ✓ |
| Ḏ/ð | 15 | ✓ | ✓ |
| ɾ | 14 | ✓ | ✓ |
| # | 13 | ✓ | ✓ |
| ˀb | 12 | ✓ | ✓ |
| ḍ/d | 11 | ✓ | ✓ |
| ˀt̪ | 11 | ✓ | ✓ |
| rː | 10 | ✓ | ✓ |
| t̪ː | 10 | ✓ | ✓ |
| ˀt | 10 | ✓ | ✓ |
| qː | 9 | ✓ | ✓ |
| ɜ | 9 | ✓ | ✓ |
| ˀn | 9 | ✓ | ✓ |
| nʲ | 8 | ✓ | ✓ |
| Z/ʒ | 7 | ✓ | ✓ |
| t̪ʷ | 6 | ✓ | ✓ |
| tʲ | 5 | ✓ | ✓ |
| yː | 5 | ✓ | ✓ |
| ɤ | 5 | ✓ | ✓ |
| ʀ | 5 | ✓ | ✓ |
| ˀr | 5 | ✓ | ✓ |
| ã | 4 | ✓ | ✓ |
| t̩/t | 4 | ✓ | ✓ |
| ˀd | 4 | ✓ | ✓ |
| cʷ | 2 | ✓ | ✓ |
| dʱ | 2 | ✓ | ✓ |
| tʃ | 2 | ✓ | ✓ |
| œ | 2 | ✓ | ✓ |
| ɐ | 2 | ✓ | ✓ |
| θ | 2 | ✓ | ✓ |
| &/e | 1 | ✓ | ✓ |
| Õ/o | 1 | ✓ | ✓ |
| f | 1 | ✓ | ✓ |
| i̱/i | 1 | ✓ | ✓ |
| lʷ | 1 | ✓ | ✓ |
| ĺ/l | 1 | ✓ | ✓ |
| n̪ː | 1 | ✓ | ✓ |
| o̱/o | 1 | ✓ | ✓ |
| ù/u | 1 | ✓ | ✓ |
| ũ | 1 | ✓ | ✓ |
| u̱/u | 1 | ✓ | ✓ |
| &#124;/l | 1 | ✓ | ✓ |
| ø | 1 | ✓ | ✓ |
| ɑː | 1 | ✓ | ✓ |
| ɛː | 1 | ✓ | ✓ |
| ˀs | 1 | ✓ | ✓ |
| ˀɭ | 1 | ✓ | ✓ |

(117 rows)



## Unsegmentable lexemes (up to 100 only)

| ID | LANGUAGE | CONCEPT | FORM |
||

(0 rows)



## Words with invalid segments (up to 100 only)

| ID | LANGUAGE | CONCEPT | FORM | SEGMENTS |
|------:|:--------------------|:------------|:----------------------------|:-----------------------------------------------------------------------------|
| 11461 | mbakwithi | grass | nhdha?a | n̪ d̪ a <s> ? </s> a |
| 11764 | mbakwithi | hair | ?ya | <s> ? </s> j a |
| 11959 | mbakwithi | hand | ?a | <s> ? </s> a |
| 12765 | mangalamck | hide | wakuyanyarri? | w a k u j a ɲ a r i <s> ? </s> |
| 13125 | bunganditj | house | natmue? wurla c | n a t m u e <s> ? </s> _ w u ɭ a _ c |
| 13294 | guuguyimidhirr | how | wondara? | w o n d a ɹ a <s> ? </s> |
| 13299 | kamilaroi | how | gwirrar? | gʷ i r a ɹ <s> ? </s> |
| 13319 | ngaanyatjarra | how | nyaaltji-nyaaltji? | ɲ aː l t c i ɲ aː l t c i <s> ? </s> |
| 13320 | ngaanyatjarra | how | yaaltji? | j aː l t c i <s> ? </s> |
| 13321 | ngaanyatjarra | how | yaaltjiwana? | j aː l t c i w a n a <s> ? </s> |
| 13322 | ngaanyatjarra | how | yaaltji-yaaltji? | j aː l t c i j aː l t c i <s> ? </s> |
| 13351 | wangkumara | how | ngalamada? | ŋ a l a m a d a <s> ? </s> |
| 13354 | warlpiri | how | nyarrpa? | ɲ a r p a <s> ? </s> |
| 13358 | warumungu | how | nyangirr? | ɲ a ŋ i r <s> ? </s> |
| 13363 | wiradjuri | how | widdyallangalu? | w i dː j a lː a ŋ a l u <s> ? </s> |
| 14296 | ngadjumaya | kill | pungu-?idja- | p u ŋ u <s> ? </s> i d c a |
| 15176 | mbakwithi | leg | thu?u | t̪ u <s> ? </s> u |
| 16935 | badjiri | mosquito | udhin? | u d̪ i n <s> ? </s> |
| 17545 | jiwarliny | name | Ngana man yiini? | ŋ g a n a _ m a n _ j iː n i <s> ? </s> |
| 18498 | mbakwithi | nonot | ngge?e | ŋ g e <s> ? </s> e |
| 19374 | wathawurrung | other | yanyuk? | j a ɲ u k <s> ? </s> |
| 19701 | warriyangga | hitwithhand | paja-? | p a c a <s> ? </s> |
| 21063 | wiradjuri | say | minnu andeyaeh? | m i nː u _ a n d e j a e h <s> ? </s> |
| 24362 | warriyangga | split | wandabala-? | w a n d a b a l a <s> ? </s> |
| 25892 | ngadjumaya | swim | wa?aandju- | w a <s> ? </s> aː n d c u |
| 26369 | mirniny | they | kajini? | k a c i n i <s> ? </s> |
| 27238 | ngamini | three | paRkuna nganha? | p a ɹ k u n a _ ŋ a n̪ a <s> ? </s> |
| 27818 | dhudhuroa | tieupfasten | guna? | g u n a <s> ? </s> |
| 27819 | dhudhuroa | tieupfasten | gana? | g a n a <s> ? </s> |
| 29064 | mbakwithi | water | pu?a | p u <s> ? </s> a |
| 29546 | biri | what | Unne tinna? | u nː e _ t i nː a <s> ? </s> |
| 29552 | dharuk | what | Ming? | m i ŋ <s> ? </s> |
| 29580 | guyani | what | nangapunu? | n a ŋ a p u n u <s> ? </s> |
| 29585 | jiwarliny | what | Ngana man julawu? | ŋ g a n a _ m a n _ c u l a w u <s> ? </s> |
| 29598 | kurnu | what | minna? | m i nː a <s> ? </s> |
| 29621 | minjungbal | what | minyung? | m i ɲ u ŋ <s> ? </s> |
| 29630 | ngaanyatjarra | what | nyaapa? | ɲ aː p a <s> ? </s> |
| 29631 | ngadjuri | what | a? | a <s> ? </s> |
| 29634 | ngarinyman | what | nyamba-warla? | ɲ a m b a w a ɭ a <s> ? </s> |
| 29672 | wangkangurru | what | mina? | m i n a <s> ? </s> |
| 29677 | warlpiri | what | nyiya? | ɲ i j a <s> ? </s> |
| 29680 | warumungu | what | nyayi? | ɲ a j i <s> ? </s> |
| 29696 | yawarrawarrka | what | mina? | m i n a <s> ? </s> |
| 29728 | gamilaraay | when | wearru? | w e a r u <s> ? </s> |
| 29741 | jiwarliny | when | Nyangurla man tikiyanku? | ŋ j a ŋ u ɭ a _ m a n _ t i k i j a n k u <s> ? </s> |
| 29743 | kamilaroi | when | wearru? | w e a r u <s> ? </s> |
| 29777 | ngarinyman | when | nyangula? | ɲ a ŋ u l a <s> ? </s> |
| 29789 | pintupiluritja | when | ngurra yaaltjingara? | ŋ u r a _ j aː l t c i ŋ a ɹ a <s> ? </s> |
| 29809 | wangkangurru | when | unkulu? | u n k u l u <s> ? </s> |
| 29812 | wangkumara | when | wani? | w a n i <s> ? </s> |
| 29840 | alyawarr | where | nthenhel? | n t̪ e n̪ e l <s> ? </s> |
| 29855 | biri | where | wunta murri? | w u n t a _ m u r i <s> ? </s> |
| 29894 | jiwarliny | where | Wanyjarrarla man warntarni? | w a ɲ c a r a ɭ a _ m a n _ w a ɳ t a ɳ i <s> ? </s> |
| 29897 | kamilaroi | where | thulla? | t̪ u lː a <s> ? </s> |
| 29903 | karuwali | where | wirdong kerna? | w i ɖ o ŋ _ k e ɳ a <s> ? </s> |
| 29935 | minjungbal | where | ille? | i lː e <s> ? </s> |
| 29946 | ngaanyatjarra | where | wanytjatja? | w a ɲ t c a t c a <s> ? </s> |
| 29947 | ngaanyatjarra | where | yaaltji? | j aː l t c i <s> ? </s> |
| 29952 | ngarinyman | where | wanyji-ga? | w a ɲ c i g a <s> ? </s> |
| 29972 | pintupiluritja | where | ngurra yaaltjingka? | ŋ u r a _ j aː l t c i ŋ k a <s> ? </s> |
| 29980 | pitjantjatjara | where | yaaltji? | j aː l t c i <s> ? </s> |
| 29996 | wangkumara | where | ngala-? | ŋ a l a <s> ? </s> |
| 29999 | warlpiri | where | nyarrpara? | ɲ a r p a ɹ a <s> ? </s> |
| 30003 | warumungu | where | wanja? wanyantta? wanjatta? | w a n c a <s> ? </s> _ w a ɲ a n tː a <s> ? </s> _ w a n c a tː a <s> ? </s> |
| 30006 | wathiwathi | where | winthaegno woortongi? | w i n t̪ a e g n o _ w oː ʈ o ŋ i <s> ? </s> |
| 30007 | watjuk | where | winjee? | w i n c eː <s> ? </s> |
| 30008 | watjuk | where | winyi? | w i ɲ i <s> ? </s> |
| 30009 | westernarrarnta | where | nthanha? | n t̪ a n̪ a <s> ? </s> |
| 30011 | wiradjuri | where | dhaga? | d̪ a g a <s> ? </s> |
| 30210 | awabakal | who | to? | t o <s> ? </s> |
| 30288 | ngaanyatjarra | who | nganalu? | ŋ a n a l u <s> ? </s> |
| 30289 | ngaanyatjarra | who | ngananya? | ŋ a n a ɲ a <s> ? </s> |
| 30292 | ngarinyman | who | ngana? | ŋ a n a <s> ? </s> |
| 30314 | pitjantjatjara | who | ngananya? | ŋ a n a ɲ a <s> ? </s> |
| 30330 | warlpiri | who | ngana? | ŋ a n a <s> ? </s> |
| 30337 | watjuk | who | nganni? | ŋ a nː i <s> ? </s> |
| 31122 | kamilaroi | work | barranbay-li? | b a r a n b a j l i <s> ? </s> |
| 31597 | mangalamck | painfulsick | warrara? | w a r a ɹ a <s> ? </s> |
| 32137 | garlali | chin | ŋanmu? | ŋ a n m u <s> ? </s> |
| 32174 | mbakwithi | chin | ngga?u | ŋ g a <s> ? </s> u |
| 32493 | mbakwithi | elbow | pAE?a | p a ɛ <s> ? </s> a |
| 33982 | pallanganmiddang | thigh | munda? | m u n d a <s> ? </s> |
| 37007 | mbakwithi | charcoal | rwi?i | r w i <s> ? </s> i |
| 37868 | pallanganmiddang | hill | padarra? | p a d a r a <s> ? </s> |
| 3799 | mbakwithi | breast | nydju?u | ɲ d c u <s> ? </s> u |
| 38016 | dhudhuroa | sandhill | mudjurru? | m u d c u r u <s> ? </s> |
| 38017 | dhudhuroa | sandhill | matjarru? | m a t c a r u <s> ? </s> |
| 38387 | wajarri | mouse | ?midu mirdu? | <s> ? </s> m i d u _ m i ɖ u <s> ? </s> |
| 4427 | dhudhuroa | climb | garrigala? | g a r i g a l a <s> ? </s> |
| 4765 | badjiri | cold | gugal? | g u g a l <s> ? </s> |
| 4779 | dharumbal | cold | bathal? | b a t̪ a l <s> ? </s> |
| 5238 | ngadjumaya | cook | wo?ana- | w o <s> ? </s> a n a |
| 5239 | ngadjumaya | cook | wo?una- | w o <s> ? </s> u n a |
| 5240 | ngadjumaya | cook | u?uni- | u <s> ? </s> u n i |
| 5241 | ngadjumaya | cook | yu?una- | j u <s> ? </s> u n a |
| 5728 | mbakwithi | cuthack | ?we?e- | ʔ w e <s> ? </s> e |
| 615 | wathawurrung | ankle | djerrin? | d c e r i n <s> ? </s> |
| 7814 | mbakwithi | ear | wa?a | w a <s> ? </s> a |
| 7867 | walmajarribilliluna | ear | manki?kir | m a n k i <s> ? </s> k i ɹ |
| 8907 | djabugay | fall | yana-y? | j a n a j <s> ? </s> |

(100 rows)

**Comment by tresoldi** [comment]
Here from Robinson Alor-Pantar:

# Detailed transcription record

## Segments

| Segment | Occurrence | BIPA | CLTS SoundClass |
|:----------|-------------:|:-------|:------------------|
| a | 3984 | ✓ | ✓ |
| i | 1940 | ✓ | ✓ |
| u | 1295 | ✓ | ✓ |
| t | 1128 | ✓ | ✓ |
| k | 1109 | ✓ | ✓ |
| l | 1031 | ✓ | ✓ |
| e | 1001 | ✓ | ✓ |
| o | 931 | ✓ | ✓ |
| r | 876 | ✓ | ✓ |
| n | 805 | ✓ | ✓ |
| m | 789 | ✓ | ✓ |
| b | 666 | ✓ | ✓ |
| ŋ | 665 | ✓ | ✓ |
| s | 525 | ✓ | ✓ |
| g | 487 | ✓ | ✓ |
| w | 472 | ✓ | ✓ |
| d | 444 | ✓ | ✓ |
| p | 408 | ✓ | ✓ |
| _ | 383 | ✓ | ✓ |
| ʔ | 326 | ✓ | ✓ |
| h | 274 | ✓ | ✓ |
| j | 230 | ✓ | ✓ |
| ə | 180 | ✓ | ✓ |
| ɛ | 167 | ✓ | ✓ |
| q | 126 | ✓ | ✓ |
| f | 125 | ✓ | ✓ |
| ħ | 101 | ✓ | ✓ |
| ɑ | 68 | ✓ | ✓ |
| v | 54 | ✓ | ✓ |
| dʒ | 50 | ✓ | ✓ |
| ʊ | 45 | ✓ | ✓ |
| ɪ | 36 | ✓ | ✓ |
| aː | 26 | ✓ | ✓ |
| tʃ | 26 | ✓ | ✓ |
| ɔ | 15 | ✓ | ✓ |
| O/ɔ | 7 | ✓ | ✓ |
| iː | 7 | ✓ | ✓ |
| V/ǝ | 6 | ✓ | ✓ |
| uː | 5 | ✓ | ✓ |
| oː | 3 | ✓ | ✓ |
| ǝ | 3 | ✓ | ✓ |
| I/ɪ | 2 | ✓ | ✓ |
| aˑ | 1 | ✓ | ✓ |
| eː | 1 | ✓ | ✓ |
| ẽ | 1 | ✓ | ✓ |
| õ | 1 | ✓ | ✓ |
| µ/u | 1 | ✓ | ✓ |
| ɒ | 1 | ✓ | ✓ |
| ɣ | 1 | ✓ | ✓ |

(49 rows)



## Unsegmentable lexemes (up to 100 only)

| ID | LANGUAGE | CONCEPT | FORM |
||

(0 rows)



## Words with invalid segments (up to 100 only)

| ID | LANGUAGE | CONCEPT | FORM | SEGMENTS |
||

(0 rows)

**Comment by LinguList** [comment]
cool! I'd say this can pass, maybe we wait for @xrotwang to have another look...

**Comment by tresoldi** [comment]
Great, better this way. :)Em 27 de abr de 2018 7:21 PM, Robert Forkel <notifications@github.com> escreveu:@xrotwang commented on this pull request.



In .travis.yml:
> @@ -6,6 +6,10 @@ python:
   - "3.6"
 cache: pip
 before_cache: rm -f $HOME/.cache/pip/log/debug.log
-install: pip install .[test] codecov
+before_install:
+    - git clone https://github.com/cldf/clts.git

@tresoldi I'll make a CLTS release to pypi - at latest on Monday. So this workaround should then be not necessary anymore.

**Comment by xrotwang** [comment]
@tresoldi why not move `pyclts` into the requirements in `setup.py`?

**Comment by tresoldi** [comment]
Sorry, isn't it there? https://github.com/lexibank/pylexibank/blob/0db755fc8b702e501871f2e6879b56a866410f9b/setup.py#L33

**Comment by xrotwang** [comment]
@tresoldi ah, yes, it is. But then we don't need the `pip install pyclts` line in `.travis.yml` :)

**Comment by tresoldi** [comment]
Of course... :flushed:

**Pull request merged**
